[versions]
agp = "8.13.1"
composeSwipeableCards = "1.1.4"
zxing = "3.5.4"
kotlin = "2.3.0"
coreKtx = "1.17.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.2"
# Will use alpha version till the material3-expressive release
# composeBom = "2025.11.01"
composeBomAlpha = "2026.01.00"
ktlint = "14.0.1"
friendlySdk = "0.0.1-dev023"
navigation = "2.9.6"
molecule = "2.2.0"
serialization = "1.9.0"
coil = "3.3.0"
exifinterface = "1.4.2"
composeBom = "2026.01.00"
lightsparkJetpackQr = "1.0.1"
ktorVersion = "3.4.0"
slf4jAndroid = "1.7.36"
desugaring = "2.0.3"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
# Will use alpha version till the material3-expressive release
#androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-bom-alpha = { group = "androidx.compose", name = "compose-bom-alpha", version.ref = "composeBomAlpha" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
lightspark-compose-qr-code = { module = "com.lightspark:compose-qr-code", version.ref = "lightsparkJetpackQr" }

coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network-ktor = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }
ktor-logging =  { module = "io.ktor:ktor-client-logging", version.ref = "ktorVersion" }
slf4j-android = { module = "org.slf4j:slf4j-android", version.ref = "slf4jAndroid" }

smartword-compose-swipeable-cards = { module = "com.github.smartword-app:compose-swipeable-cards", version.ref = "composeSwipeableCards" }
zxing-core = { module = "com.google.zxing:core", version.ref = "zxing" }
molecule = { module = "app.cash.molecule:molecule-runtime", version.ref = "molecule" }

friendly-sdk = { module = "me.y9san9.friendly:sdk", version.ref = "friendlySdk" }

serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
androidx-exifinterface = { group = "androidx.exifinterface", name = "exifinterface", version.ref = "exifinterface" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycleRuntimeKtx" }
android-tools-desugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugaring" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
