name: Android CI

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:

jobs:
    build:
        permissions: "write-all"
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4

            -   uses: actions/setup-java@v4
                with:
                  distribution: temurin
                  java-version: 21

            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v5

            -   name: Decode keystore
                run: echo "$KEYSTORE_BASE64" | base64 --decode > keystore.jks

            -   name: Build debug with signing
                run: ./gradlew assembleDebug

            -   name: Upload artifacts
                uses: actions/upload-artifact@v4
                with:
                    name: android-app
                    path: app/build/outputs/apk/debug/app-debug.apk

            -   name: Deploy Apk
                uses: WebFreak001/deploy-nightly@v3.2.0
                with:
                  upload_url: https://uploads.github.com/repos/friendly-social/android/releases/280899065/assets{?name,label}
                  release_id: 280899065
                  asset_path: app/build/outputs/apk/debug/app-debug.apk
                  asset_name: friendly-latest.apk
                  asset_content_type: application/zip
                  max_releases: 1
                  ignore_hash: true
